spring:
  profiles:
    include:
      - datasource
      - auth
      - s3
      - azure
      - redis
      - openai

  config:
    import: optional:file:.env[.properties]

  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  base-uri: ${SERVER_URI}
  port: 8080

cors:
  allowed-origins: http://localhost:3000, https://ttobaki.app

logging:
  level:
    com.example.GoSonGim_BE: DEBUG
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json