spring:
  profiles:
    include:
      - datasource
      - auth
      - s3
      - azure
      - redis
      #- openai  # TODO: 대화 생성 API 구현 시 활성화

  config:
    import: optional:file:.env[.properties]

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  base-uri: ${SERVER_URI}
  port: 8080

cors:
  allowed-origins: http://localhost:3000

logging:
  level:
    com.example.GoSonGim_BE: DEBUG
    org.springframework.security: DEBUG