spring:
  config:
    activate:
      on-profile: auth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              # - profile
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v2/userinfo"
            user-name-attribute: name

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 86400000  # 24시간 (밀리초)
  refresh-token:
    expiration: 1209600000  # 14일 (밀리초)