spring:
  config:
    activate:
      on-profile: s3

aws:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ap-northeast-2
    bucket: ttobak-audio
    image-bucket: ${S3_IMAGE_BUCKET:ttobak-images}
